apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo001
  name: demo001
  namespace: nju11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo001
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        app: demo001
    spec:
      containers:
        - image: harbor.edu.cn/nju11/demo001:{VERSION}
          name: demo001
      imagePullSecrets:
          - name: nju11
---
apiVersion: v1
kind: Service
metadata:
  name: demo001
  namespace: nju11
  labels:
    app: demo001
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31111
  selector:
    app: demo001